import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#003543",
        "on-surface-variant": "#bbc9cf",
        "on-error": "#690005",
        "vibrant-cyan": "#22D3EE",
        "on-primary-fixed-variant": "#004e60",
        "inverse-primary": "#00677f",
        "surface-container-high": "#262a36",
        "on-background": "#dfe2f2",
        "outline-variant": "#3c494e",
        "outline": "#859399",
        "on-tertiary": "#003640",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-variant": "#313441",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004e5c",
        "inverse-surface": "#dfe2f2",
        "on-secondary-fixed-variant": "#5516be",
        "on-tertiary-fixed": "#001f26",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#005766",
        "on-secondary-container": "#c4abff",
        "primary": "#a4e6ff",
        "surface-container": "#1b1f2b",
        "tertiary-container": "#43d1f0",
        "secondary-container": "#571bc1",
        "on-primary-fixed": "#001f28",
        "primary-fixed-dim": "#4cd6ff",
        "deep-slate": "#0B0F1A",
        "secondary-fixed-dim": "#d0bcff",
        "primary-fixed": "#b7eaff",
        "on-surface": "#dfe2f2",
        "inverse-on-surface": "#2c303c",
        "neon-purple": "#8B5CF6",
        "secondary": "#d0bcff",
        "surface-container-low": "#171b27",
        "background": "#0f131e",
        "surface-bright": "#353945",
        "surface-container-highest": "#313441",
        "surface-dim": "#0f131e",
        "surface": "#0f131e",
        "on-secondary-fixed": "#23005c",
        "surface-dark": "#161B28",
        "primary-container": "#00d1ff",
        "on-secondary": "#3c0091",
        "tertiary": "#96e9ff",
        "surface-container-lowest": "#0a0e19",
        "on-primary-container": "#00566a",
        "tertiary-fixed": "#acedff",
        "error": "#ffb4ab",
        "electric-blue": "#00D1FF",
        "surface-tint": "#4cd6ff"
      },
      fontFamily: {
        sora: ["var(--font-sora)"],
        inter: ["var(--font-inter)"],
        mono: ["var(--font-jetbrains-mono)"],
      },
      animation: {
        'spin-slow': 'spin 8s linear infinite',
      },
    },
  },
  plugins: [],
};
export default config;
